insert into [words] values ( "男性",  "だんせい", "đàn ông" )
insert into [words] values ( "女性",  "じょせい", "phụ nữ" )
insert into [words] values ( "高齢",  "こうれい", "cao tuổi" )
insert into [words] values ( "年上",  "としうえ", "hơn tuổi" )
insert into [words] values ( "目上",  "めうえ", "bề trên" )
insert into [words] values ( "先輩",  "せんぱい", "tiền bối" )
insert into [words] values ( "後輩",  "こうはい", "hậu bối" )
insert into [words] values ( "上司",  "じょうし", "cấp trên" )
insert into [words] values ( "相手",  "あいて", "người đối diện" )
insert into [words] values ( "知り合い",  "しりあい", "người quen" )
insert into [words] values ( "友人",  "ゆうじん", "bạn bè" )
insert into [words] values ( "仲",  "なか", "mối quan hệ" )
insert into [words] values ( "生年月日",  "せいねんがっぴ", "ngày tháng năm sinh" )
insert into [words] values ( "誕生",  "たんじょう", "ra đời" )
insert into [words] values ( "年",  "とし", "niên năm" )
insert into [words] values ( "出身",  "しゅっしん", "quê quán" )
insert into [words] values ( "故郷",  "こきょう", "cố hương" )
insert into [words] values ( "成長",  "せいちょう", "trưởng thành" )
insert into [words] values ( "成人",  "せいじん", "người trưởng thành" )
insert into [words] values ( "合格",  "ごうかく", "đỗ đại học" )
insert into [words] values ( "進学",  "しんがく", "vào đại học" )
insert into [words] values ( "退学",  "たいがく", "bỏ học" )
insert into [words] values ( "就職",  "しゅうしょく", "có việc làm" )
insert into [words] values ( "退職",  "たいしょく", "nghỉ việc" )
insert into [words] values ( "失業",  "しつぎょう", "thất nghiệp" )
insert into [words] values ( "残業",  "ざんぎょう", "làm thêm" )
insert into [words] values ( "生活",  "せいかつ", "cuộc sống" )
insert into [words] values ( "通勤",  "つうきん", "đi làm" )
insert into [words] values ( "学歴",  "がくれき", "bằng cấp" )
insert into [words] values ( "給料",  "きゅうりょう", "tiền lương" )
insert into [words] values ( "面接",  "めんせつ", "phỏng vấn" )
insert into [words] values ( "休憩",  "きゅうけい", "nghỉ ngơi" )
insert into [words] values ( "観光",  "かんこう", "tham quan" )
insert into [words] values ( "帰国",  "きこく", "về nước" )
insert into [words] values ( "帰省",  "きせい", "về quê" )
insert into [words] values ( "帰宅",  "きたく", "về nhà" )
insert into [words] values ( "参加",  "さんか", "tham gia" )
insert into [words] values ( "出席",  "しゅっせき", "có mặt" )
insert into [words] values ( "欠席",  "けっせき", "vắng mặt" )
insert into [words] values ( "遅刻",  "ちこく", "đến muộn" )
insert into [words] values ( "化粧",  "けしょう", "trang điểm" )
insert into [words] values ( "計算",  "けいさん", "tính toán" )
insert into [words] values ( "計画",  "けいかく", "kế hoạch" )
insert into [words] values ( "成功",  "せいこう", "thành công" )
insert into [words] values ( "失敗",  "しっぱい", "thất bại" )
insert into [words] values ( "準備",  "じゅんび", "chuẩn bị" )
insert into [words] values ( "整理",  "せいり", "chỉnh sửa" )
insert into [words] values ( "注文",  "ちゅうもん", "đặt hàng" )
insert into [words] values ( "貯金",  "ちょきん", "tiết kiệm" )
insert into [words] values ( "徹夜",  "てつや", "thức xuyên đêm" )
insert into [words] values ( "引っ越し",  "ひっこし", "chuyển nhà" )
insert into [words] values ( "身長",  "しんちょう", "chiều cao" )
insert into [words] values ( "体重",  "たいじゅう", "cân nặng" )
insert into [words] values ( "けが",  "けが", "vết thương" )
insert into [words] values ( "会",  "かい", "hội" )
insert into [words] values ( "趣味",  "しゅみ", "sở thích" )
insert into [words] values ( "興味",  "きょうみ", "hứng thú" )
insert into [words] values ( "思い出",  "おもいで", "nhớ lại" )
insert into [words] values ( "冗談",  "じょうだん", "đùa cợt" )
insert into [words] values ( "目的",  "もくてき", "mục đích" )
insert into [words] values ( "約束",  "やくそく", "lời hứa" )
insert into [words] values ( "おしゃべり",  "おしゃべり", "nói chuyện riêng" )
insert into [words] values ( "遠慮",  "えんりょ", "ngại ngần" )
insert into [words] values ( "我慢",  "がまん", "chịu đựng" )
insert into [words] values ( "目枠",  "めわく", "làm phiền" )
insert into [words] values ( "希望",  "きぼう", "hi vọng" )
insert into [words] values ( "夢",  "ゆめ", "giấc mơ" )
insert into [words] values ( "賛成",  "さんせい", "đồng ý" )
insert into [words] values ( "反対",  "はんたい", "đối lập" )
insert into [words] values ( "創造",  "そうぞう", "tưởng tượng" )
insert into [words] values ( "努力",  "どりょく", "nỗ lực" )
insert into [words] values ( "太陽",  "たいよう", "mặt trời" )
insert into [words] values ( "地球",  "ちきゅう", "trái đất" )
insert into [words] values ( "温度",  "おんど", "nhiệt độ" )
insert into [words] values ( "湿度",  "しつど", "độ ẩm" )
insert into [words] values ( "湿気",  "しっけ", "hơi ẩm" )
insert into [words] values ( "梅雨",  "つゆ", "mùa mưa" )
insert into [words] values ( "かび",  "かび", "nấm mốc" )
insert into [words] values ( "暖房",  "だんぼう", "điều hòa ấm" )
insert into [words] values ( "皮",  "かわ", "da" )
insert into [words] values ( "館",  "かん", "quán" )
insert into [words] values ( "画面",  "がめん", "màn hình" )
insert into [words] values ( "番組",  "ばんぐみ", "chương trình" )
insert into [words] values ( "記事",  "きじ", "ký sự" )
insert into [words] values ( "近所",  "きんじょ", "xung quanh" )
insert into [words] values ( "警察",  "けいさつ", "cảnh sát" )
insert into [words] values ( "犯人",  "はんにん", "tội phạm" )
insert into [words] values ( "小銭",  "こぜに", "tiền lẻ" )
insert into [words] values ( "ごちそう",  "ごちそう", "chiêu đãi" )
insert into [words] values ( "作者",  "作者", "tác giả" )
insert into [words] values ( "作品",  "さくひん", "tác phẩm" )
insert into [words] values ( "制服",  "せいふく", "đồng phục" )
insert into [words] values ( "洗剤",  "せんざい", "bột giặt" )
insert into [words] values ( "底",  "そこ", "đáy" )
insert into [words] values ( "地下",  "ちか", "ngầm" )
insert into [words] values ( "寺",  "てら", "chùa" )
insert into [words] values ( "道路",  "どうろ", "đường" )
insert into [words] values ( "坂",  "さか", "dốc" )
insert into [words] values ( "煙",  "けむり", "khói" )
insert into [words] values ( "灰",  "はい", "tàn, tro" )
insert into [words] values ( "判",  "はん", "con dấu" )
insert into [words] values ( "名刺",  "めいし", "danh thiếp" )
insert into [words] values ( "免許",  "めんきょ", "giấy phép" )
insert into [words] values ( "多く",  "おおく", "nhiều" )
insert into [words] values ( "前半",  "ぜんはん", "phần đầu" )
insert into [words] values ( "後半",  "こうはん", "phần cuối" )
insert into [words] values ( "最高",  "さいこう", "cao nhất" )
insert into [words] values ( "最低",  "さいてい", "thấp nhất" )
insert into [words] values ( "最初",  "さいしょ", "đầu tiên" )
insert into [words] values ( "最後",  "さいご", "cuối cùng" )
insert into [words] values ( "自動",  "じどう", "tự động" )
insert into [words] values ( "種類",  "しゅるい", "loại" )
insert into [words] values ( "性格",  "せいかく", "tính cách" )
insert into [words] values ( "性質",  "せいしつ", "tính chất" )
insert into [words] values ( "順番",  "じゅんばん", "thứ tự" )
insert into [words] values ( "番",  "ばん", "lượt" )
insert into [words] values ( "方法",  "ほうほう", "phương pháp" )
insert into [words] values ( "製品",  "せいひん", "sản phẩm" )
insert into [words] values ( "値上がり",  "ねあがり", "tăng giá" )
insert into [words] values ( "生",  "なま", "(hải sản) tươi" )
insert into [words] values ( "節約",  "せつやく", "tiết kiệm" )
insert into [words] values ( "経営",  "けいえい", "quản lý" )
insert into [words] values ( "反省",  "はんせい", "tự kiểm tra" )
insert into [words] values ( "実行",  "じっこう", "thực hành" )
insert into [words] values ( "進歩",  "しんぽ", "tiến bộ" )
insert into [words] values ( "変化",  "へんか", "thay hóa" )
insert into [words] values ( "発達",  "はったつ", "phát triển" )
insert into [words] values ( "体力",  "たいりょく", "thể lực" )
insert into [words] values ( "出場",  "しゅつじょう", "tham dự" )
insert into [words] values ( "活躍",  "かつやく", "hoạt động" )
insert into [words] values ( "競争",  "きょうそう", "cạnh tranh" )
insert into [words] values ( "応援",  "おうえん", "cổ vũ" )
insert into [words] values ( "拍手",  "はくしゅ", "vỗ tay" )
insert into [words] values ( "人気",  "にんき", "nổi tiếng" )
insert into [words] values ( "うわさ",  "うわさ", "tin đồn" )
insert into [words] values ( "情報",  "じょうほう", "thông tin" )
insert into [words] values ( "交換",  "こうかん", "trao đổi" )
insert into [words] values ( "流行",  "りゅうこう", "trào lưu" )
insert into [words] values ( "宣伝",  "せんでん", "tuyên truyền" )
insert into [words] values ( "広告",  "こうこく", "quảng cáo" )
insert into [words] values ( "注目",  "ちゅうもく", "chú trọng" )
insert into [words] values ( "通訳",  "つうやく", "thông dịch" )
insert into [words] values ( "翻訳",  "ほにゃく", "phiên. Dịch biên dịch" )
insert into [words] values ( "伝言",  "でんごん", "tin nhắn thoại" )
insert into [words] values ( "報告",  "ほうこく", "báo cáo" )
insert into [words] values ( "録画",  "ろくが", "ghi lại" )
insert into [words] values ( "混雑",  "こんざつ", "hỗn tạp" )
insert into [words] values ( "渋滞",  "じゅうたい", "tắc đường" )
insert into [words] values ( "衝突",  "しょうとつ", "xung đột" )
insert into [words] values ( "被害",  "ひがい", "thiệt hại" )
insert into [words] values ( "事故",  "じこ", "tai nạn" )
insert into [words] values ( "事件",  "じけん", "sự kiện" )
insert into [words] values ( "故障",  "こしょう", "hỏng" )
insert into [words] values ( "修理",  "しゅうり", "sửa chữa" )
insert into [words] values ( "停電",  "ていでん", "mất điện" )
insert into [words] values ( "調子",  "ちょうし", "trạng thái" )
insert into [words] values ( "緊張",  "きんちょう", "lo lắng" )
insert into [words] values ( "自身",  "じしん", "tự tin" )
insert into [words] values ( "自慢",  "じまん", "tự mãn" )
insert into [words] values ( "感心",  "かんしん", "quan tâm" )
insert into [words] values ( "感動",  "かんどう", "cảm động" )
insert into [words] values ( "興奮",  "こうふん", "hưng phấn" )
insert into [words] values ( "感想",  "かんそう", "cảm tưởng" )
insert into [words] values ( "予想",  "よそう", "dự đoán" )
insert into [words] values ( "専門",  "せんもん", "chuyên môn" )
insert into [words] values ( "研究",  "けんきゅう", "nghiên cứu" )
insert into [words] values ( "調査",  "ちょうさ", "điều tra" )
insert into [words] values ( "原因",  "げんいん", "nguyên nhân" )
insert into [words] values ( "結果",  "けっか", "kết quả" )
insert into [words] values ( "解決",  "かいけつ", "giải quyết" )
insert into [words] values ( "確認",  "かくにん", "xác nhận" )
insert into [words] values ( "利用",  "りよう", "sử dụng" )
insert into [words] values ( "理解",  "りかい", "lý giải" )
insert into [words] values ( "発見",  "はっけん", "phát kiến" )
insert into [words] values ( "発明",  "はつめい", "phát minh" )
insert into [words] values ( "関係",  "かんけい", "quan hệ" )
insert into [words] values ( "団体",  "だんたい", "đoàn thể" )
insert into [words] values ( "選挙",  "せんきょ", "bầu cử" )
insert into [words] values ( "税金",  "ぜいきん", "thuế" )
insert into [words] values ( "責任",  "trách", "nhiệm" )
insert into [words] values ( "書類",  "しょるい", "tài liệu" )
insert into [words] values ( "題名",  "だいめい", "tiêu đề" )
insert into [words] values ( "条件",  "じょうけん", "điều kiện" )
insert into [words] values ( "締め切り",  "しめきり", "hạn cuối" )
insert into [words] values ( "期間",  "きかん", "thời kỳ" )
insert into [words] values ( "倍",  "ばい", "lần" )
insert into [words] values ( "くじ",  "くじ", "xổ thăm" )
insert into [words] values ( "近道",  "ちかみち", "đường tắt" )
insert into [words] values ( "中心",  "ちゅうしん", "trung tâm" )
insert into [words] values ( "辺り",  "あたり", "biên cận" )
insert into [words] values ( "周り",  "まわり", "chu xung quanh" )
insert into [words] values ( "穴",  "あな", "lỗ" )
insert into [words] values ( "列",  "れつ", "hàng" )
insert into [words] values ( "幅",  "はば", "chiều rộng" )
insert into [words] values ( "範囲",  "はんい", "phạm vi" )
insert into [words] values ( "内容",  "ないよう", "nội dung" )
insert into [words] values ( "中身",  "なかみ", "bên trong" )
insert into [words] values ( "特徴",  "とくちょう", "đặc trưng" )
insert into [words] values ( "普通",  "ふつう", "bình thường" )
insert into [words] values ( "当たり前",  "あたりまえ", "đương nhiên" )
insert into [words] values ( "偽",  "にせ", "ngụy giả" )
insert into [words] values ( "別",  "べつ", "biệt khác" )
insert into [words] values ( "国籍",  "こくせき", "quốc tịch" )
insert into [words] values ( "東洋",  "とうよう", "phương đông" )
insert into [words] values ( "西洋",  "せいよう", "phương tây" )
insert into [words] values ( "国際",  "こくさい", "quốc tế" )
insert into [words] values ( "自然",  "しぜん", "tự nhiên" )
insert into [words] values ( "景色",  "けしき", "phong cảnh" )
insert into [words] values ( "宗教",  "しゅうきょう", "tôn giáo" )
insert into [words] values ( "愛",  "あい", "yêu yêu" )
insert into [words] values ( "実は",  "じつは", "thực tế là" )
insert into [words] values ( "読書",  "どくしょ", "đọc viết" )
insert into [words] values ( "演奏",  "えんそう", "biểu diễn" )
insert into [words] values ( "芸術",  "げいじゅつ", "nghệ thuật" )
insert into [words] values ( "検査",  "けんさ", "kiểm tra" )
insert into [words] values ( "血液",  "けつえき", "máu" )
insert into [words] values ( "治療",  "ちりょう", "trị liệu" )
insert into [words] values ( "症状",  "しょうじょう", "triệu chứng" )
insert into [words] values ( "予防",  "よぼう", "dự phòng" )
insert into [words] values ( "栄養",  "えいよう", "dinh dưỡng" )
insert into [words] values ( "手術",  "しゅじゅつ", "phẫu thuật" )
insert into [words] values ( "死亡",  "しぼう", "tử vong" )
insert into [words] values ( "命",  "いのち", "mệnh sinh mạng" )
insert into [words] values ( "一生",  "いっしょう", "suốt đời" )
insert into [words] values ( "誤解",  "ごかい", "hiểu nhầm" )
insert into [words] values ( "後悔",  "こうかい", "hối hận" )
insert into [words] values ( "訳",  "わけ", "dịch lý do" )
insert into [words] values ( "態度",  "たいど", "thái độ" )
insert into [words] values ( "癖",  "くせ", "thói quen" )
insert into [words] values ( "礼儀",  "れいぎ", "lễ nghĩa" )
insert into [words] values ( "文句",  "もんく", "phàn nàn" )
insert into [words] values ( "表情",  "ひょうじょう", "biểu thị" )
insert into [words] values ( "鏡面",  "ひょうめん", "bề mặt" )
insert into [words] values ( "禁煙",  "きんえん", "cấm hút thuốc" )
insert into [words] values ( "禁止",  "きんし", "cấm" )
insert into [words] values ( "完成",  "かんせい", "hoàn thành" )
insert into [words] values ( "課題",  "かだい", "chủ đề" )
insert into [words] values ( "例外",  "れいがい", "ngoại lệ" )
insert into [words] values ( "基本",  "きほん", "cơ bản" )
insert into [words] values ( "記録",  "きろく", "ghi âm" )
insert into [words] values ( "状態",  "じょうたい", "trạng thái" )
insert into [words] values ( "出来事",  "できごと", "sự kiện" )
insert into [words] values ( "場面",  "ばめん", "khung trường" )
insert into [words] values ( "機会",  "きかい", "cơ hội" )
insert into [words] values ( "距離",  "きょり", "khoảng cách" )
insert into [words] values ( "提案",  "ていあん", "đề xuất" )
insert into [words] values ( "やり取り",  "やりとり", "trao việc" )
insert into [words] values ( "知識",  "ちしき", "kiến thức" )
insert into [words] values ( "実力",  "じつりょく", "thực lực" )
insert into [words] values ( "手段",  "しゅだん", "cách thức" )
insert into [words] values ( "代表",  "だいひょう", "đại biểu" )
insert into [words] values ( "影響",  "えいきょう", "ảnh hưởng" )
insert into [words] values ( "効果",  "こうか", "hiệu quả" )
insert into [words] values ( "印象",  "いんしょう", "ấn tượng" )
insert into [words] values ( "印",  "しるし", "ấn hiệu" )
insert into [words] values ( "合図",  "あいず", "ám hiệu" )
insert into [words] values ( "共通",  "きょうつう", "chung" )
insert into [words] values ( "協調",  "きょうちょう", "nhấn mạnh" )
insert into [words] values ( "省略",  "しょうりゃく", "lược bớt" )
insert into [words] values ( "挑戦",  "ちょうせん", "thử thách" )
insert into [words] values ( "やる気",  "やるき", "khí động lực" )
insert into [words] values ( "勇気",  "ゆうき", "dũng khí" )
insert into [words] values ( "資格",  "しかく", "bằng cách" )
insert into [words] values ( "申請",  "しんせい", "đăng tuyển" )
insert into [words] values ( "本人",  "ほんにん", "được nói đến" )
insert into [words] values ( "契約",  "けいやく", "hợp đồng" )
insert into [words] values ( "証明",  "しょうめい", "chứng chứng" )
insert into [words] values ( "変更",  "へんこう", "thay đổi" )
insert into [words] values ( "保存",  "ほぞん", "bảo tồn" )
insert into [words] values ( "保護",  "ほご", "bảo vệ" )
insert into [words] values ( "環境",  "かんきょう", "môi trường" )
insert into [words] values ( "資源",  "しげん", "tài nguyên" )
insert into [words] values ( "不足",  "ふそく", "thiếu" )
insert into [words] values ( "平均",  "へいきん", "trung bình" )
insert into [words] values ( "割合",  "わりあい", "tỷ lệ" )
insert into [words] values ( "商売",  "しょうばい", "kinh bán" )
insert into [words] values ( "商品",  "しょうひん", "sản phẩm" )
insert into [words] values ( "質",  "しつ", "chất lượng" )
insert into [words] values ( "型",  "かた", "hình mẫu" )
insert into [words] values ( "生産",  "せいさん", "sản xuất" )
insert into [words] values ( "消費",  "しょうひ", "tiêu thụ" )
insert into [words] values ( "物価",  "ぶっか", "giá giá" )
insert into [words] values ( "倒産",  "とうさん", "phá sản" )
insert into [words] values ( "携帯",  "けいたい", "mang theo" )
insert into [words] values ( "現代",  "げんだい", "hiện tại" )
insert into [words] values ( "世紀",  "せいき", "thế kỷ" )
insert into [words] values ( "文化",  "ぶんか", "văn hóa" )
insert into [words] values ( "都市",  "とし", "thành phố" )
insert into [words] values ( "地方",  "ちほう", "địa phương" )
insert into [words] values ( "戦争",  "せんそう", "chiến tranh" )
insert into [words] values ( "平和",  "へいわ", "hòa bình" )
insert into [words] values ( "クラスメート",  "クラスメート", "bạn cùng lớp " )
insert into [words] values ( "グループ",  "グループ", "nhóm " )
insert into [words] values ( "チーム",  "チーム", "đội " )
insert into [words] values ( "プロフェッショナル",  "プロフェッショナル", "chuyên nghiệp " )
insert into [words] values ( "アマチュア",  "アマチュア", "nghiệp dư " )
insert into [words] values ( "トレーニング",  "トレーニング", "đào tạo " )
insert into [words] values ( "マッサージ",  "マッサージ", "mát xa " )
insert into [words] values ( "アドバイス",  "アドバイス", "khuyên " )
insert into [words] values ( "アイデア・アイディア",  "アイデア・アイディア", "ý tưởng" )
insert into [words] values ( "トップ",  "トップ", "top" )
insert into [words] values ( "スピード",  "スピード", "tốc độ" )
insert into [words] values ( "ラッシュ",  "ラッシュ", "đông đúc" )
insert into [words] values ( "バイク",  "バイク", "xe máy" )
insert into [words] values ( "ヘルメット",  "ヘルメット", "mũ bảo hiểm" )
insert into [words] values ( "コンタクトレンズ",  "コンタクトレンズ", "kính áp tròng" )
insert into [words] values ( "ガラス",  "ガラス", "kính" )
insert into [words] values ( "プラスチック",  "プラスチック", "nhựa" )
insert into [words] values ( "ベランダ",  "ベランダ", "ban công" )
insert into [words] values ( "ペット",  "ペット", "thú cưng" )
insert into [words] values ( "ベンチ",  "ベンチ", "ghế bành" )
insert into [words] values ( "デザイン",  "デザイン", "thiết kế" )
insert into [words] values ( "バーゲンセール",  "バーゲンセール", "sale" )
insert into [words] values ( "パート",  "パート", "làm thêm" )
insert into [words] values ( "コンビニエンスストア",  "コンビニエンスストア", "cửa hàng tiện ích" )
insert into [words] values ( "レジ",  "レジ", "máy tính tiền" )
insert into [words] values ( "レシート",  "レシート", "hóa đơn" )
insert into [words] values ( "インスタント",  "インスタント", "ăn liền" )
insert into [words] values ( "ファストフード",  "ファストフード", "đồ ăn nhanh" )
insert into [words] values ( "フルーツ",  "フルーツ", "trái cây" )
insert into [words] values ( "デザート",  "デザート", "tráng miệng" )
insert into [words] values ( "インターネット",  "インターネット", "internet" )
insert into [words] values ( "チャイム",  "チャイム", "chuông" )
insert into [words] values ( "アナウンス",  "アナウンス", "thông báo" )
insert into [words] values ( "メッセージ",  "メッセージ", "tin nhắn" )
insert into [words] values ( "パンフレット",  "パンフレット", "tờ rơi" )
insert into [words] values ( "カード",  "カード", "card" )
insert into [words] values ( "インタビュー",  "インタビュー", "phỏng vấn" )
insert into [words] values ( "アンケート",  "アンケート", "tờ câu hỏi" )
insert into [words] values ( "データ",  "データ", "dữ liệu" )
insert into [words] values ( "パーセント",  "パーセント", "phần trăm" )
insert into [words] values ( "パートナ",  "パートナー", "đối tác" )
insert into [words] values ( "リーダー",  "リーダー", "lãnh đạo" )
insert into [words] values ( "ボランティア",  "ボランティア", "tình nguyện" )
insert into [words] values ( "コミュニケーション",  "コミュニケーション", "giao tiếp" )
insert into [words] values ( "ユーモア",  "ユーモア", "hài" )
insert into [words] values ( "ショック",  "ショック", "sốc" )
insert into [words] values ( "ストレス",  "ストレス", "căng" )
insert into [words] values ( "バランス",  "バランス", "cân bằng" )
insert into [words] values ( "レベル",  "レベル", "trình" )
insert into [words] values ( "アップ",  "アップ", "tăng lên" )
insert into [words] values ( "ダウン",  "ダウン", "giảm xuống" )
insert into [words] values ( "プラス",  "プラス", "phép động tích cực" )
insert into [words] values ( "マイナス",  "マイナス", "phép động tiêu cực" )
insert into [words] values ( "イメージ",  "イメージ", "hình ảnh" )
insert into [words] values ( "コンテスト",  "コンテスト", "cuộc thi" )
insert into [words] values ( "マスコミ",  "マスコミ", "thông tin truyền thông" )
insert into [words] values ( "プライバシー",  "プライバシー", "cá tư" )
insert into [words] values ( "オフィス",  "オフィス", "văn phòng" )
insert into [words] values ( "ルール",  "ルール", "luật lệ" )
insert into [words] values ( "マナー",  "マナー", "tác phong" )
insert into [words] values ( "ミス",  "ミス", "lỗi" )
insert into [words] values ( "スケジュール",  "スケジュール", "hoạch" )
insert into [words] values ( "タイトル",  "タイトル", "tiêu đề" )
insert into [words] values ( "テーマ",  "テーマ", "chủ đề" )
insert into [words] values ( "ストーリー",  "ストーリー", "câu chuyện" )
insert into [words] values ( "ヒット",  "ヒット", "nổi tiếng" )
insert into [words] values ( "ブランド",  "ブランド", "nhãn hiệu" )
insert into [words] values ( "レンタル",  "レンタル", "thuê" )
insert into [words] values ( "リサイクル",  "リサイクル", "tái chế" )
insert into [words] values ( "ラベル",  "ラベル", "nhãn" )
insert into [words] values ( "タイプ",  "タイプ", "loại" )
insert into [words] values ( "スタイル",  "スタイル", "kiểu dáng" )
insert into [words] values ( "セット",  "セット", "cài" )
insert into [words] values ( "ウイルス",  "ウイルス", "virus" )
insert into [words] values ( "ロボット",  "ロボット", "robot" )
insert into [words] values ( "エネルギー",  "エネルギー", "năng lượng" )
insert into [words] values ( "デジタル",  "デジタル", "kỹ thuật số" )
insert into [words] values ( "マイク",  "マイク", "âm" )
insert into [words] values ( "ブレーキ",  "ブレーキ", "phanh" )
insert into [words] values ( "ペンキ",  "ペンキ", "sơn" )
insert into [words] values ( "幸せな",  "しあわせな", "hạnh phúc " )
insert into [words] values ( "得意な",  "とくいな"," " )
insert into [words] values ( "苦手な",  "にがてな"," " )
insert into [words] values ( "熱心な",  "ねっしんな", "chăm chỉ " )
insert into [words] values ( "夢中な",  "むちゅうな", "chú tâm " )
insert into [words] values ( "退屈な",  "たいくつな", "chán " )
insert into [words] values ( "健康な",  "けんこうな", "khỏe khoắn " )
insert into [words] values ( "苦しい",  "くるしい", "cực khổ " )
insert into [words] values ( "平気な",  "へいきな", "bình thản" )
insert into [words] values ( "悔しい",  "くやしい", "cay cú" )
insert into [words] values ( "うらやましい",  "うらやましい", "ghen tỵ" )
insert into [words] values ( "かゆい",  "かゆい", "ngứa" )
insert into [words] values ( "おとなしい",  "おとなしい", "trầm lặng" )
insert into [words] values ( "我慢強い",  "がまんづよい", "chịu đựng giỏi" )
insert into [words] values ( "正直な",  "しょうじきな", "trung thực" )
insert into [words] values ( "けちな",  "けちな", "kẹt xỉ" )
insert into [words] values ( "我儘な",  "ích", "kỷ" )
insert into [words] values ( "積極的な",  "せっきょくてきな", "tích cực" )
insert into [words] values ( "消極的な",  "しょうきょくてきな", "tiêu cực" )
insert into [words] values ( "満足な",  "まんぞくな", "thỏa mãn" )
insert into [words] values ( "不満な",  "ふまんな", "bất mãn" )
insert into [words] values ( "不安な",  "ふあんな", "bất an" )
insert into [words] values ( "大変な",  "たいへんな", "tồi tệ" )
insert into [words] values ( "無理な",  "むりな", "vô lý" )
insert into [words] values ( "不注意な",  "ふちゅういな", "không chú ý" )
insert into [words] values ( "楽な",  "らくな", "lạc thoải mái" )
insert into [words] values ( "面倒な",  "めんどうな", "phiền phức" )
insert into [words] values ( "失礼な",  "しつれいな", "thất lễ" )
insert into [words] values ( "当然な",  "とうぜんな", "đương nhiên" )
insert into [words] values ( "意外な",  "いがいな", "không ngờ đến" )
insert into [words] values ( "結構な",  "けっこうな", "khá là" )
insert into [words] values ( "派手な",  "はでな", "lòe loẹt" )
insert into [words] values ( "地味な",  "じみな", "giản dị" )
insert into [words] values ( "おしゃれな",  "おしゃれな", "thời" )
insert into [words] values ( "変な",  "へんな", "biến lạ" )
insert into [words] values ( "不思議な",  "ふしぎな", "thần bí" )
insert into [words] values ( "ましな",  "ましな", "tốt lên" )
insert into [words] values ( "むだな",  "むだな", "lãng phí" )
insert into [words] values ( "自由な",  "じゆうな", "tự do" )
insert into [words] values ( "不自由な",  "ふじゆうな", "không tự do" )
insert into [words] values ( "濃い",  "こい", "nồng" )
insert into [words] values ( "薄い",  "うすい", "mỏng, nhạt" )
insert into [words] values ( "酸っぱい",  "すっぱい", "chua" )
insert into [words] values ( "臭い",  "くさい", "thối" )
insert into [words] values ( "おかしい",  "おかしい", "lạ" )
insert into [words] values ( "かっこいい",  "かっこいい", "bảnh bao" )
insert into [words] values ( "うまい",  "うまい", "ngon" )
insert into [words] values ( "親しい",  "したしい", "thân thiết" )
insert into [words] values ( "詳しい",  "くわしい", "chi tiết" )
insert into [words] values ( "細かい",  "こまかい", "cặn kẽ, tỉ mỉ" )
insert into [words] values ( "浅い",  "あさい", "nông" )
insert into [words] values ( "固い・硬い",  "かたい", "cứng" )
insert into [words] values ( "ぬるい",  "ぬるい", "nguội" )
insert into [words] values ( "まぶしい",  "まぶしい", "chói" )
insert into [words] values ( "蒸し暑い",  "むしあつい", "nóng ẩm" )
insert into [words] values ( "清潔な",  "せいけつな", "sạch" )
insert into [words] values ( "新鮮な",  "しんせんな", "tươi" )
insert into [words] values ( "豊かな",  "ゆたかな", "giàu có" )
insert into [words] values ( "立派な",  "りっぱな", "lập siêu" )
insert into [words] values ( "正確な",  "せいかくな", "chính xác" )
insert into [words] values ( "確かな",  "たしかな", "đích thực" )
insert into [words] values ( "重要な",  "じゅうような", "quan trọng" )
insert into [words] values ( "必要な",  "ひつような", "cần thiết" )
insert into [words] values ( "もったいない",  "もったいない", "lãng phí" )
insert into [words] values ( "すごい",  "すごい", "tuyệt" )
insert into [words] values ( "ひどい",  "ひどい", "tồi" )
insert into [words] values ( "激しい",  "はげしい", "mãnh liệt" )
insert into [words] values ( "そっくりな",  "そっくりな", "giống" )
insert into [words] values ( "急な",  "きゅうな", "đột nhiên" )
insert into [words] values ( "敵とな",  "てきとな", "phù hợp" )
insert into [words] values ( "特別な",  "とくべつな", "đặc biệt" )
insert into [words] values ( "完全な",  "かんぜんな", "toàn bộ" )
insert into [words] values ( "盛んな",  "さかんな", "thịnh vượng" )
insert into [words] values ( "様々な",  "さまざまな", "đa đạng" )
insert into [words] values ( "可能な",  "かのうな", "khả thi" )
insert into [words] values ( "不可能な",  "ふかのうな", "bất khả thi" )
insert into [words] values ( "基本的な",  "きほんてきな", "cơ bản" )
insert into [words] values ( "国際的な",  "こくさいてきな", "tính quốc tế" )
insert into [words] values ( "ばらばらな",  "ばらばらな", "tung rẽ" )
insert into [words] values ( "ぼろぼろな",  "ぼろぼろな", "rách tua" )
insert into [words] values ( "大変に",  "たいへんに", "khủng nhiều " )
insert into [words] values ( "ほとんど",  "ほとんど", "gần như hoàn toàn " )
insert into [words] values ( "大体",  "だいたい", "phần khoảng " )
insert into [words] values ( "かなり",  "かなり", "khá " )
insert into [words] values ( "ずいぶん",  "ずいぶん", "đáng kể " )
insert into [words] values ( "けっこう",  "けっこう", "rất " )
insert into [words] values ( "大分",  "ずいぶん", "chủ " )
insert into [words] values ( "もっと",  "もっと", "hơn nữa" )
insert into [words] values ( "しっかり",  "しっかり", "toàn bộ" )
insert into [words] values ( "いっぱい",  "いっぱい", "đầy" )
insert into [words] values ( "ぎりぎり",  "ぎりぎり", "nút" )
insert into [words] values ( "ぴったり",  "ぴったり", "vừa" )
insert into [words] values ( "たいてい",  "たいてい", "đại" )
insert into [words] values ( "同時に",  "どうじに", "cùng lúc" )
insert into [words] values ( "前もって",  "まえもって", "tiền trước" )
insert into [words] values ( "すぐに",  "すぐに", "ngay lập tức" )
insert into [words] values ( "もうすぐ",  "もうすぐ", "sắp" )
insert into [words] values ( "突然",  "とつぜん", "đột nhiên" )
insert into [words] values ( "あっという間に",  "あっというまに", "loáng một cái" )
insert into [words] values ( "いつの間にか",  "いつのまにか", "lúc nào không biết" )
insert into [words] values ( "しばらく",  "しばらく", "một chút" )
insert into [words] values ( "ずっと",  "ずっと", "nhất định" )
insert into [words] values ( "相変わらず",  "あいかわらず", "như mọi khi" )
insert into [words] values ( "次々に",  "つぎつぎに", "lần lượt" )
insert into [words] values ( "どんどん",  "どんどん", "dần dần" )
insert into [words] values ( "ますます",  "ますます", "càng ngày càng" )
insert into [words] values ( "やっと",  "やっと", "cuối đủ" )
insert into [words] values ( "とうとう",  "とうとう", "sau tất cả" )
insert into [words] values ( "ついに",  "ついに", "cuối cùng" )
insert into [words] values ( "もちろん",  "もちろん", "tất nhiên" )
insert into [words] values ( "やはり",  "やはり", "như dự tính" )
insert into [words] values ( "きっと",  "きっと", "nhất định" )
insert into [words] values ( "ぜひ",  "ぜひ", "bằng mọi (muốn)" )
insert into [words] values ( "なるべく",  "なるべく", "càng nhiều càng tốt" )
insert into [words] values ( "案外",  "あんがい", "không ngờ đến" )
insert into [words] values ( "もしかすると・もしかしたら・もしかして",  "có", "lẽ" )
insert into [words] values ( "まさか",  "まさか", "không thể" )
insert into [words] values ( "うっかり",  "うっかり", "ngơ để ý" )
insert into [words] values ( "つい",  "つい", "vô" )
insert into [words] values ( "思わず",  "おもわず", "tư không ngờ đến" )
insert into [words] values ( "ほっと",  "ほっと", "yên tâm" )
insert into [words] values ( "いらいら",  "いらいら", "khó giận" )
insert into [words] values ( "のんびり",  "のんびり", "tận hưởng" )
insert into [words] values ( "ぐっすり",  "ぐっすり", "say" )
insert into [words] values ( "きちんと",  "きちんと", "ngay ngắn" )
insert into [words] values ( "しっかり",  "しっかり", "kiên tin cậy" )
insert into [words] values ( "はっきり",  "はっきり", "rõ ràng" )
insert into [words] values ( "じっと",  "じっと", "kiên chằm" )
insert into [words] values ( "そっと",  "そっと", "nhẹ lặng" )
insert into [words] values ( "別々に",  "べつべつに", "riêng biệt" )
insert into [words] values ( "それぞれ",  "それぞれ", "lần ứng" )
insert into [words] values ( "互いに",  "たがいに", "lẫn nhau" )
insert into [words] values ( "直接",  "ちょくせつ", "trực tiếp" )
insert into [words] values ( "本当に",  "ほんとうに", "thật thực" )
insert into [words] values ( "必ず",  "かならず", "chắc chắn" )
insert into [words] values ( "絶対に",  "ぜったいに", "chắc chắn rồi" )
insert into [words] values ( "特に",  "とくに", "đặc biệt là" )
insert into [words] values ( "ただ",  "ただ", "chỉ" )
insert into [words] values ( "少なくとも",  "すくなくとも", "ít nhất" )
insert into [words] values ( "決して",  "けっして", "không bao giờ" )
insert into [words] values ( "少しも",  "すこしも", "một chút" )
insert into [words] values ( "ちっとも",  "ちっとも", "(không) tí gì" )
insert into [words] values ( "全く",  "まったく", "hoàn toàn (không)" )
insert into [words] values ( "とても",  "とても", "rất" )
insert into [words] values ( "どんなに",  "どんなに", "thế nào cũng" )
insert into [words] values ( "どうしても",  "どうしても", "kiểu gì cũng" )
insert into [words] values ( "まるで",  "まるで", "như là" )
insert into [words] values ( "一体",  "いったい", "nói chung" )
insert into [words] values ( "別に",  "べつに", "đặc biệt" )
insert into [words] values ( "たった",  "たった", "chỉ" )
insert into [words] values ( "ほんの",  "ほんの", "một chút" )
insert into [words] values ( "それで",  "それで", "thế thì" )
insert into [words] values ( "そこで",  "そこで", "tiếp theo" )
insert into [words] values ( "そのうえ",  "そのうえ", "hơn nữa" )
insert into [words] values ( "また",  "また", "nữa" )
insert into [words] values ( "または",  "または", "hoặc" )
insert into [words] values ( "それとも",  "それとも", "hoặc" )
insert into [words] values ( "つまり",  "つまり", "nói cách khác" )
insert into [words] values ( "渇く",  "かわく", "khát khát " )
insert into [words] values ( "嗅ぐ",  "かぐ", "xúy ngửi " )
insert into [words] values ( "叩く",  "たたく", "khấu " )
insert into [words] values ( "殴る",  "なぐる", "ẩu đấm " )
insert into [words] values ( "ける",  "ける", "đá " )
insert into [words] values ( "抱く",  "だく", "bão ôm " )
insert into [words] values ( "倒れる",  "たおれる", "đảo đổ " )
insert into [words] values ( "倒す",  "たおす", "đảo làm đổ " )
insert into [words] values ( "起きる",  "おきる", "thức dậy" )
insert into [words] values ( "起こす",  "おこす", "đánh thức" )
insert into [words] values ( "尋ねる",  "たずねる", "hỏi" )
insert into [words] values ( "呼ぶ",  "よぶ", "gọi" )
insert into [words] values ( "叫ぶ",  "さけぶ", "gào to" )
insert into [words] values ( "黙る",  "だまる", "im lặng" )
insert into [words] values ( "飼う",  "かう", "nuôi" )
insert into [words] values ( "数える",  "かぞえる", "đếm" )
insert into [words] values ( "乾く",  "かわく", "khô" )
insert into [words] values ( "乾かす",  "かわかす", "làm khô" )
insert into [words] values ( "畳む",  "たたむ", "gấp" )
insert into [words] values ( "誘う",  "さそう", "mời" )
insert into [words] values ( "おごる",  "おごる", "chiêu đãi" )
insert into [words] values ( "預かる",  "あずかる", "chăm sóc" )
insert into [words] values ( "預ける",  "あずける", "gửi" )
insert into [words] values ( "決まる",  "きまる", "được quyết định" )
insert into [words] values ( "決める",  "きめる", "quyết định" )
insert into [words] values ( "写る",  "うつる", "chụp được" )
insert into [words] values ( "写す",  "うつす", "chụp" )
insert into [words] values ( "思い出す",  "おもいだす", "tự nhớ lại" )
insert into [words] values ( "教わる",  "おそわる", "được dạy" )
insert into [words] values ( "申し込む",  "もうしこむ", "đăng ký" )
insert into [words] values ( "断る",  "ことわる", "từ chối" )
insert into [words] values ( "見つかる",  "みつかる", "được tìm thấy" )
insert into [words] values ( "見つける",  "みつける", "tìm thấy" )
insert into [words] values ( "捕まる",  "つかまる", "bị bắt" )
insert into [words] values ( "捕まえる",  "つかまえる", "bắt" )
insert into [words] values ( "乗る",  "のる", "leo lên" )
insert into [words] values ( "乗せる",  "のせる", "cho lên" )
insert into [words] values ( "降りる",  "おりる", "xuống" )
insert into [words] values ( "降ろす",  "おろす", "cho xuống" )
insert into [words] values ( "直る",  "なおる", "được sửa" )
insert into [words] values ( "直す",  "なおす", "sửa" )
insert into [words] values ( "治る",  "なおる", "hồi phục" )
insert into [words] values ( "治す",  "なおす", "cứu chữa" )
insert into [words] values ( "亡くなる",  "なくなる", "chết" )
insert into [words] values ( "亡くす",  "なくす", "mất" )
insert into [words] values ( "生まれる",  "うまれる", "được sinh ra" )
insert into [words] values ( "生む",  "うむ", "sinh" )
insert into [words] values ( "出会う",  "であう", "gặp (ngẫu nhiên)" )
insert into [words] values ( "訪ねる",  "たずねる", "thăm" )
insert into [words] values ( "付き合う",  "つきあう", "hẹn tiếp" )
insert into [words] values ( "効く",  "きく", "có hiệu quả" )
insert into [words] values ( "はやる",  "はやる", "phổ biến" )
insert into [words] values ( "経つ",  "たつ", "qua" )
insert into [words] values ( "間に合う",  "まにあう", "làm cho kịp giờ" )
insert into [words] values ( "間に合わせる",  "まにあわせる", "kịp giờ" )
insert into [words] values ( "通う",  "かよう", "đi" )
insert into [words] values ( "込む",  "こむ", "đông" )
insert into [words] values ( "すれ違う",  "すれちあう", "vi" )
insert into [words] values ( "掛かる",  "かかる", "được bao phủ" )
insert into [words] values ( "掛ける",  "かける", "bao phủ" )
insert into [words] values ( "動く",  "うごく", "hoạt động" )
insert into [words] values ( "動かす",  "うごかす", "di chuyển" )
insert into [words] values ( "離れる",  "はなれる", "tránh xa" )
insert into [words] values ( "離す",  "はなす", "tách ra" )
insert into [words] values ( "ぶつかる",  "ぶつかる", "bị đâm" )
insert into [words] values ( "ぶつける",  "ぶつける", "đâm" )
insert into [words] values ( "こぼれる",  "こぼれる", "bị tràn" )
insert into [words] values ( "こぼす",  "こぼす", "tràn" )
insert into [words] values ( "ふく",  "ふく", "lau" )
insert into [words] values ( "片付く",  "かたづく", "được dọn dẹp" )
insert into [words] values ( "片付ける",  "かたづける", "dọn dẹp" )
insert into [words] values ( "包む",  "つつむ", "bao bọc" )
insert into [words] values ( "張る",  "はる", "trương dán" )
insert into [words] values ( "無くなる",  "なくなる", "bị mất" )
insert into [words] values ( "無くす",  "なくす", "mất" )
insert into [words] values ( "足りる",  "たりる", "túc đủ" )
insert into [words] values ( "残る",  "のこる", "bị thừa" )
insert into [words] values ( "残す",  "のこす", "thừa" )
insert into [words] values ( "腐る",  "くさる", "thối" )
insert into [words] values ( "むける",  "むける", "bị lột" )
insert into [words] values ( "むく",  "むく", "lột" )
insert into [words] values ( "滑る",  "すべる", "trượt" )
insert into [words] values ( "積もる",  "つもる", "được tích tụ" )
insert into [words] values ( "積む",  "つむ", "tích lại" )
insert into [words] values ( "空く",  "あく", "bị thủng" )
insert into [words] values ( "空ける",  "あける", "thủng" )
insert into [words] values ( "下がる",  "さがる", "bị giảm" )
insert into [words] values ( "下げる",  "さげる", "giảm" )
insert into [words] values ( "冷える",  "ひえる", "bị lạnh" )
insert into [words] values ( "冷やす",  "ひやす", "làm lạnh" )
insert into [words] values ( "冷める",  "さめる", "bị nguội" )
insert into [words] values ( "冷ます",  "さます", "làm nguội" )
insert into [words] values ( "燃える",  "もえる", "bị cháy" )
insert into [words] values ( "燃やす",  "もやす", "đốt" )
insert into [words] values ( "沸く",  "わく", "sôi" )
insert into [words] values ( "沸かす",  "わかす", "đun sôi" )
insert into [words] values ( "鳴る",  "なる", "kêu" )
insert into [words] values ( "鳴らす",  "ならす", "làm kêu" )
insert into [words] values ( "役立つ",  "やくだつ", "hữu ích" )
insert into [words] values ( "役立てる",  "やくだてる", "được sử dụng" )
insert into [words] values ( "飾り",  "かざり", "trang trí" )
insert into [words] values ( "遊び",  "あそび", "chơi" )
insert into [words] values ( "集まり",  "あつまり", "tập hợp" )
insert into [words] values ( "教え",  "おしえ", "dạy" )
insert into [words] values ( "踊り",  "おどり", "nhảy" )
insert into [words] values ( "思い",  "おもい", "nghĩ" )
insert into [words] values ( "考え",  "かんがえ", "suy nghĩ" )
insert into [words] values ( "片づけ",  "かたづけ", "ngăn nắp" )
insert into [words] values ( "手伝い",  "てつだい", "giúp đỡ" )
insert into [words] values ( "働き",  "はたらき", "hoạt động" )
insert into [words] values ( "決まり",  "きまり", "luật lệ" )
insert into [words] values ( "騒ぎ",  "さわぎ", "ồn ào" )
insert into [words] values ( "知らせ",  "しらせ", "tin báo" )
insert into [words] values ( "頼み",  "たのみ", "yêu cầu" )
insert into [words] values ( "疲れ",  "つかれ", "vất mỏi" )
insert into [words] values ( "違い",  "ちがい", "khác biệt" )
insert into [words] values ( "始め",  "はじめ", "khởi đầu" )
insert into [words] values ( "続き",  "つづき", "tiếp tục" )
insert into [words] values ( "暮れ",  "くれ", "cuối ngày (mùa, năm)" )
insert into [words] values ( "行き",  "いき", "đi" )
insert into [words] values ( "帰り",  "かえり", "trở về" )
insert into [words] values ( "急ぎ",  "いそぎ", "khẩn cấp" )
insert into [words] values ( "遅れ",  "おくれ", "gián đoạn" )
insert into [words] values ( "貸し",  "かし", "cho mượn" )
insert into [words] values ( "借り",  "かり", "mượn" )
insert into [words] values ( "勝ち",  "かち", "thắng" )
insert into [words] values ( "負け",  "まけ", "thua" )
insert into [words] values ( "迎え",  "むかえ", "đón" )
insert into [words] values ( "始まり",  "はじまり", "bắt đầu" )
insert into [words] values ( "終わり",  "おわり", "kết thúc" )
insert into [words] values ( "戻り",  "もどり", "trở lại" )
insert into [words] values ( "別れ",  "わかれ", "chia ly" )
insert into [words] values ( "喜び",  "よろこび", "hớn hở" )
insert into [words] values ( "楽しみ",  "たのしみ", "sung sướng" )
insert into [words] values ( "笑い",  "わらい", "cười" )
insert into [words] values ( "驚き",  "おどろき", "ngạc nhiên" )
insert into [words] values ( "怒り",  "いかり", "giận dữ" )
insert into [words] values ( "悲しみ",  "かたしみ", "buồn bã" )
insert into [words] values ( "温まる",  "あたたまる", "trở nên ấm hơn" )
insert into [words] values ( "温める",  "あたためる", "làm ấm" )
insert into [words] values ( "高まる",  "たかまる", "cao lên" )
insert into [words] values ( "高める",  "たかめる", "làm cao lên" )
insert into [words] values ( "強まる",  "つよまる", "mạnh lên" )
insert into [words] values ( "強める",  "つよめる", "làm mạnh lên" )
insert into [words] values ( "弱まる",  "よわまる", "yếu đi" )
insert into [words] values ( "弱める",  "よわめる", "làm yếu đi" )
insert into [words] values ( "広まる",  "ひろまる", "rộng ra" )
insert into [words] values ( "広める",  "ひろめる", "làm rộng ra" )
insert into [words] values ( "深まる",  "ふかまる", "sâu hơn" )
insert into [words] values ( "深める",  "ふかめる", "làm sâu thêm" )
insert into [words] values ( "世話",  "せわ", "chăm sóc" )
insert into [words] values ( "家庭",  "かてい", "gia đình" )
insert into [words] values ( "協力",  "きょうりょく", "hiệp lực" )
insert into [words] values ( "感謝",  "かんしゃ", "cảm tạ" )
insert into [words] values ( "お礼",  "おれい", "đáp lễ" )
insert into [words] values ( "お詫び",  "おわび", "xin lỗi" )
insert into [words] values ( "おじぎ",  "おじぎ", "cúi chào" )
insert into [words] values ( "握手",  "あくしゅ", "bắt tay" )
insert into [words] values ( "いじわる",  "いじわる", "xấu bụng" )
insert into [words] values ( "いたずら",  "いたずら", "nghịch ngợm" )
insert into [words] values ( "届く",  "とどく", "được giao đến" )
insert into [words] values ( "届ける",  "とどける", "giao đến" )
insert into [words] values ( "かく",  "かく", "gãi" )
insert into [words] values ( "つかむ",  "つかむ", "nắm bắt" )
insert into [words] values ( "握る",  "にぎる", "nắm chặt" )
insert into [words] values ( "抑える",  "おさえる", "giữ" )
insert into [words] values ( "近づく",  "ちかづく", "lại gần" )
insert into [words] values ( "近づける",  "ちかづける", "mang đến gần" )
insert into [words] values ( "合う",  "あう", "gặp" )
insert into [words] values ( "合わせる",  "あわせる", "tập lực" )
insert into [words] values ( "当たる",  "あたる", "bị đánh" )
insert into [words] values ( "当てる",  "あてる", "đánh" )
insert into [words] values ( "比べる",  "くらべる", "so sánh" )
insert into [words] values ( "似合う",  "にあう", "hợp" )
insert into [words] values ( "似る",  "にる", "giống" )
insert into [words] values ( "似せる",  "にせる", "bắt chước" )
insert into [words] values ( "分かれる",  "わかれる", "được chia ra" )
insert into [words] values ( "分ける",  "わける", "chia" )
insert into [words] values ( "足す",  "たす", "thêm vào" )
insert into [words] values ( "引く",  "ひく", "dẫn, kéo" )
insert into [words] values ( "増える",  "ふえる", "tăng lên" )
insert into [words] values ( "増やす",  "ふやす", "làm tăng lên" )
insert into [words] values ( "減る",  "へる", "giảm xuống" )
insert into [words] values ( "減らす",  "へらす", "làm giảm xuống" )
insert into [words] values ( "変わる",  "かわる", "thay đổi" )
insert into [words] values ( "変える",  "かえる", "làm thay đổi" )
insert into [words] values ( "代わる・替わる・換わる",  "かわる", "thay" )
insert into [words] values ( "代える・替える・換える",  "かえる", "đổi" )
insert into [words] values ( "返る",  "かえる", "được trả lại" )
insert into [words] values ( "返す",  "かえす", "trả lại" )
insert into [words] values ( "譲る",  "ゆずる", "nhường" )
insert into [words] values ( "助かる",  "たすかる", "được giúp" )
insert into [words] values ( "助ける",  "たすける", "giúp" )
insert into [words] values ( "いじめる",  "いじめる", "bắt nạt" )
insert into [words] values ( "だまる",  "だまる", "lừa" )
insert into [words] values ( "盗む",  "ぬすむ", "lấy cắp" )
insert into [words] values ( "刺さる",  "ささる", "bị đâm" )
insert into [words] values ( "刺す",  "さす", "đâm" )
insert into [words] values ( "殺す",  "ころす", "giết" )
insert into [words] values ( "隠れる",  "かくれる", "ẩn" )
insert into [words] values ( "隠す",  "かくす", "che giấu" )
insert into [words] values ( "埋まる",  "うまる", "bị chôn" )
insert into [words] values ( "埋める",  "うめる", "chôn" )
insert into [words] values ( "囲む",  "かこむ", "vây quanh" )
insert into [words] values ( "詰まる",  "つまる", "tắc, kẹt" )
insert into [words] values ( "詰める",  "つめる", "chôn, lấp, cắt giảm, " )
insert into [words] values ( "開く",  "ひらく", "mở" )
insert into [words] values ( "閉じる",  "とじる", "đóng" )
insert into [words] values ( "飛ぶ",  "とぶ", "bay" )
insert into [words] values ( "飛ばす",  "とばす", "cho bay" )
insert into [words] values ( "振る",  "ふる", "chỉ định, đóng vai" )
insert into [words] values ( "めくる",  "めくる", "lật lên" )
insert into [words] values ( "見かける",  "みかける", "tình cờ thấy" )
insert into [words] values ( "確かめる",  "たしかめる", "kiểm tra lại" )
insert into [words] values ( "試す",  "ためす", "thử" )
insert into [words] values ( "繰り返す",  "くりかえす", "lặp lại" )
insert into [words] values ( "訳す",  "やくす", "dịch" )
insert into [words] values ( "行う",  "おこなう", "tổ chức" )
insert into [words] values ( "間違う",  "まちがう", "bị sai" )
insert into [words] values ( "間違える",  "まちがえる", "làm sai" )
insert into [words] values ( "許す",  "ゆるす", "tha phép" )
insert into [words] values ( "慣れる",  "なれる", "quen" )
insert into [words] values ( "慣らす",  "ならす", "thuần hóa, làm cho quen" )
insert into [words] values ( "立つ",  "たつ", "đứng" )
insert into [words] values ( "立てる",  "たてる", "dựng lên" )
insert into [words] values ( "建つ",  "たつ", "được xây" )
insert into [words] values ( "建てる",  "たてる", "xây" )
insert into [words] values ( "育つ",  "そだつ", "được nuôi dạy" )
insert into [words] values ( "育てる",  "そだてる", "nuôi dạy" )
insert into [words] values ( "生える",  "はえる", "mọc" )
insert into [words] values ( "生やす",  "はやす", "nuôi(râu)" )
insert into [words] values ( "汚れる",  "よごれる", "bị bẩn" )
insert into [words] values ( "汚す",  "よごす", "làm bẩn" )
insert into [words] values ( "壊れる",  "こわれる", "bị hỏng" )
insert into [words] values ( "壊す",  "こわす", "làm hỏng" )
insert into [words] values ( "割れる",  "われる", "bị vỡ" )
insert into [words] values ( "割る",  "わる", "làm vỡ" )
insert into [words] values ( "折れる",  "おれる", "bị gãy" )
insert into [words] values ( "折る",  "おる", "làm gãy" )
insert into [words] values ( "破れる",  "やぶれる", "bị rách" )
insert into [words] values ( "破る",  "やぶる", "xé rách" )
insert into [words] values ( "曲がる",  "まがる", "bị uốn cong" )
insert into [words] values ( "曲げる",  "まげる", "uốn cong" )
insert into [words] values ( "外れる",  "はずれる", "bị rời ra" )
insert into [words] values ( "外す",  "はずす", "tách ra" )
insert into [words] values ( "揺れる",  "ゆれる", "bị rung" )
insert into [words] values ( "揺らす",  "ゆらす", "đung đưa" )
insert into [words] values ( "流れる",  "ながれる", "chảy" )
insert into [words] values ( "流す",  "ながす", "cho chảy" )
insert into [words] values ( "濡れる",  "ぬれる", "bị ướt" )
insert into [words] values ( "濡らす",  "ぬらす", "làm ướt" )
insert into [words] values ( "迷う",  "まよう", "lạc đường" )
insert into [words] values ( "悩む",  "なやむ", "băn khoăn" )
insert into [words] values ( "慌てる",  "あわてる", "vội vàng" )
insert into [words] values ( "覚める",  "さめる", "thức dậy" )
insert into [words] values ( "覚ます",  "さます", "mở" )
insert into [words] values ( "眠る",  "ねむる", "ngủ" )
insert into [words] values ( "祈る",  "いのる", "cầu nguyện" )
insert into [words] values ( "祝う",  "いわう", "ăn mừng" )
insert into [words] values ( "感じる",  "かんじる", "cảm thấy" )
insert into [words] values ( "上る",  "のぼる", "leo lên" )
insert into [words] values ( "下る",  "くだる", "đi xuống" )
insert into [words] values ( "進む",  "すすむ", "tiến lên" )
insert into [words] values ( "進める",  "すすめる", "làm cho tiến lên" )
insert into [words] values ( "通る",  "とおる", "đi ngang qua" )
insert into [words] values ( "通す",  "とおす", "xuyên qua" )
insert into [words] values ( "超える・越える",  "こえる", "vượt qua" )
insert into [words] values ( "過ぎる",  "すぎる", "qua" )
insert into [words] values ( "過ごす",  "すごす", "sử dụng(thời gian)" )
insert into [words] values ( "移る",  "うつる", "được chuyển" )
insert into [words] values ( "移す",  "うつす", "chuyển" )
insert into [words] values ( "連れる",  "つれる", "dẫn đi" )
insert into [words] values ( "寄る",  "よる", "ghé gần" )
insert into [words] values ( "寄せる",  "よせる", "ghé vào" )
insert into [words] values ( "与える",  "あたえる", "cấp" )
insert into [words] values ( "得る",  "える", "đạt được" )
insert into [words] values ( "向く",  "むく", "hướng đến, thích hợp với" )
insert into [words] values ( "向ける",  "むける", "hướng về phía" )
insert into [words] values ( "勧める",  "すすめる", "gợi ý" )
insert into [words] values ( "薦める",  "すすめる", "khuyến khích" )
insert into [words] values ( "任せる",  "まかせる", "hết sức, dốc lòng/phó thác" )
insert into [words] values ( "守る",  "まもる", "bảo vệ" )
insert into [words] values ( "争う",  "あらそう", "gây gỗ, tranh giành" )
insert into [words] values ( "臨む",  "のぞむ", "ước" )
insert into [words] values ( "信じる",  "しんじる", "tin tưởng" )
insert into [words] values ( "通じる",  "つうじる", "dẫn đến, hiểu rõ" )
insert into [words] values ( "飽きる",  "あきる", "chán, mệt mỏi, không hứng thú" )
insert into [words] values ( "思いつく",  "おもいつく", "chợt nghĩ ra" )
insert into [words] values ( "思いやる",  "おもいやる", "cảm thông, ân cần" )
insert into [words] values ( "熱中する",  "ねっちゅうする", "hăng say, nghiện" )
insert into [words] values ( "暮らす",  "くらす", "sống" )
insert into [words] values ( "巻く",  "まく", "quấn" )
insert into [words] values ( "結ぶ",  "むすぶ", "kết lại, buộc, nối" )
insert into [words] values ( "済む",  "すむ", "kết thúc" )
insert into [words] values ( "すませる・済ます",  "hoàn", "tất" )
insert into [words] values ( "出来る",  "できる", "có thể làm được" )
insert into [words] values ( "切れる",  "きれる", "bị đứt, bị gãy, hết hạn" )
insert into [words] values ( "切らす",  "きらす", "dùng hết, hết hàng" )
insert into [words] values ( "伝わる",  "つたわる", "được truyền tải" )
insert into [words] values ( "伝える",  "つたえる", "truyền tải" )
insert into [words] values ( "続く",  "つづく", "tiếp sau" )
insert into [words] values ( "続ける",  "つづける", "liên tiếp" )
insert into [words] values ( "つながる",  "つながる", "có liên hệ" )
insert into [words] values ( "つなぐ",  "つなぐ", "kết nối" )
insert into [words] values ( "つなげる",  "つなげる", "kết chặt thêm" )
insert into [words] values ( "伸びる",  "のびる", "(tự) lớn ra" )
insert into [words] values ( "伸ばす",  "のばす", "kéo ra" )
insert into [words] values ( "延びる",  "のびる", "bị trì kéo dài" )
insert into [words] values ( "延ばす",  "のばす", "trì dài" )
insert into [words] values ( "重なる",  "かさなる", "trùng với, chồng chất" )
insert into [words] values ( "重ねる",  "かさねる", "chồng lên" )
insert into [words] values ( "広がる",  "ひろがる", "(bị) mở rộng ra" )
insert into [words] values ( "広げる",  "ひろげる", "mở rộng ra" )
insert into [words] values ( "載る",  "のる", "được công bố" )
insert into [words] values ( "載せる",  "のせる", "công bố" )
insert into [words] values ( "揃う",  "そろう", "được chuẩn bị sẵn sàng" )
insert into [words] values ( "揃える",  "そろえる", "thu thập, chuẩn bị sẵn sàng" )
insert into [words] values ( "まとまる",  "まとまる", "được sắp xếp" )
insert into [words] values ( "まとめる",  "まとめる", "sắp xếp vào trật tự" )
insert into [words] values ( "付く",  "つく", "dính" )
insert into [words] values ( "付ける",  "つける", "dính vào" )
insert into [words] values ( "たまる",  "たまる", "được tiết kiệm" )
insert into [words] values ( "ためる",  "ためる", "tiết kiệm" )
insert into [words] values ( "交じる・混じる",  "まじる", "giao vào" )
insert into [words] values ( "交ざる・混ざる",  "まざる", "được trộn lẫn" )
insert into [words] values ( "交ぜる・混ぜる",  "まぜる", "trộn vào" )
insert into [words] values ( "解ける・溶ける",  "とける", "bị tuột, chảy ra" )
insert into [words] values ( "解く・溶く",  "とく", "làm tuột, chảy ra" )
insert into [words] values ( "含む",  "ふくむ", "gồm" )
insert into [words] values ( "含める",  "ふくめる", "bao gồm" )
insert into [words] values ( "抜ける",  "ぬける", "rút ra, rút lui, rụng" )
insert into [words] values ( "抜く",  "ぬく", "lấy ra, rút ra" )
insert into [words] values ( "現れる",  "あらわれる", "xuất hiện, lộ diện" )
insert into [words] values ( "現す",  "あらわす", "thể hiện ra, làm xuất ra" )
insert into [words] values ( "表れる",  "あらわれる", "biểu hiện (trên mặt)" )
insert into [words] values ( "表す",  "あらわす", "biểu diện" )
insert into [words] values ( "散る",  "ちる", "bị héo, tàn" )
insert into [words] values ( "散らす",  "ちらす", "tàn" )
insert into [words] values ( "明ける",  "あける", "rạng sáng, hé lộ" )
insert into [words] values ( "差す",  "さす", "(mặt trời) chiếu" )
insert into [words] values ( "炊ける",  "たける", "được nấu" )
insert into [words] values ( "炊く",  "たく", "nấu" )
insert into [words] values ( "煮える",  "にえる", "được ninh" )
insert into [words] values ( "煮る",  "にる", "ninh" )
insert into [words] values ( "炒める",  "いためる", "rán" )
insert into [words] values ( "焼ける",  "やける", "được nướng" )
insert into [words] values ( "焼く",  "やく", "nướng" )
insert into [words] values ( "ゆでる",  "ゆでる", "luộc" )
insert into [words] values ( "揚げる",  "あげる", "rán ngập" )
insert into [words] values ( "蒸す",  "むす", "hấp" )